// Generated by CoffeeScript 1.4.0
(function() {
  var EQTokenizer, NumberValue, eqt;

  NumberValue = require('../../src/parser/NumberValue');

  eqt = require('../../src/parser/EQTokenizer');

  EQTokenizer = eqt.EQTokenizer;

  describe("A Tokenizer", function() {
    var getVar;
    getVar = function(variable) {
      if (variable === "x") {
        return 5;
      } else {
        return null;
      }
    };
    it("exists in the calculator", function() {
      return expect(EQTokenizer).toBeDefined();
    });
    return it("Can split a statement into its component parts", function() {
      var list;
      console.log("hi");
      EQTokenizer.tokenize("1 + 1", getVar);
      list = EQTokenizer.getList();
      expects(list).toBe(["1", "+", "1"]);
      EQTokenizer.tokenize("2 - 2", getVar);
      list = EQTokenizer.getList();
      expects(list).toBe(["2", "-", "2"]);
      EQTokenizer.tokenize("3 * 4", getVar);
      list = EQTokenizer.getList();
      expects(list).toBe(["3", "*", "4"]);
      EQTokenizer.tokenize("10 / 2", getVar);
      list = EQTokenizer.getList();
      expects(list).toBe(["10", "/", "2"]);
      EQTokenizer.tokenize("sin(x)", getVar);
      list = EQTokenizer.getList();
      return expects(list).toBe(["sin(", "x", ")"]);
    });
  });

}).call(this);
