// Generated by CoffeeScript 1.6.1
(function() {

  describe("A Tokenizer", function() {
    var getVar;
    getVar = function(variable) {
      if (variable === "x") {
        return 5;
      } else {
        return null;
      }
    };
    it("exists in the calculator", function() {
      return expect(EQTokenizer).toBeDefined();
    });
    it("can split a statement into its component parts", function() {
      var list;
      EQTokenizer.tokenize("1 + 1", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["1", "+", "1"]);
      EQTokenizer.tokenize("2 - 2", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["2", "-", "2"]);
      EQTokenizer.tokenize("3 * 4", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["3", "*", "4"]);
      EQTokenizer.tokenize("10 / 2", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["10", "/", "2"]);
      EQTokenizer.tokenize("sin(x)", getVar);
      list = EQTokenizer.getList();
      return expect(list).toEqual(["sin(", "x", ")"]);
    });
    return it("can handle negative numbers", function() {
      var list;
      EQTokenizer.tokenize("-1 + 2", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["-1", "+", "2"]);
      EQTokenizer.tokenize("2 - 2", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["2", "-", "2"]);
      EQTokenizer.tokenize("3 * -4", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["3", "*", "-4"]);
      EQTokenizer.tokenize("300+7-2", getVar);
      list = EQTokenizer.getList();
      expect(list).toEqual(["300", "+", "7", "-", "2"]);
      EQTokenizer.tokenize("(10) - 2", getVar);
      list = EQTokenizer.getList();
      return expect(list).toEqual(["(", "10", ")", "-", "2"]);
    });
  });

}).call(this);
