// Generated by CoffeeScript 1.4.0
(function() {

  describe("A TreeBuilder", function() {
    it("can calculate expressions", function() {
      var comparison, number, result;
      result = EQParser.parse("1+1");
      number = new NumberValue("2");
      comparison = result.compareTo(number);
      return expect(comparison).toEqual(0);
    });
    return it("exists in the calculator", function() {
      return expect(EQTreeBuilder).toBeDefined();
    });
  });

}).call(this);
